version: '3.9'
services:
    # databases
    postgis:
        image: valtimo-academy-postgis:0.0.9
        container_name: valtimo-academy-postgis
        platform: linux/amd64
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - PGDATA=/data
    postgres:
        image: valtimo-academy-postgres:0.0.7
        container_name: valtimo-academy-postgres
        platform: linux/amd64
        ports: 
            - "54321:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - PGDATA=/data
            
    #hulp services
    redis:
        image: redis:6.2.6
        container_name: valtimo-academy-redis
    rabbitmq:
        image: rabbitmq:3.9-management
        container_name: valtimo-academy-rabbitmq
        expose:
            - 5673
            - 15673
        ports:
            - "5673:5673"
            - "15673:15673"
        
    #zgw services    
    openzaak:
        image: openzaak/open-zaak:1.5.0
        container_name: valtimo-academy-openzaak
        platform: linux/amd64
        environment:
            - DB_HOST=postgis
            - DB_POST=5432
            - SECRET_KEY=veryRestrictedSecretKey
            - DB_USER=postgres
            - DB_PASSWORD=postgres
            - DB_NAME=openzaak
            - CACHE_DEFAULT=redis:6379/0
            - CACHE_AXES=redis:6379/0
            - DEBUG=true
            - ALLOWED_HOSTS=localhost,host.docker.internal,172.17.0.1,openzaak
            - SENDFILE_BACKEND=django_sendfile.backends.simple
        ports:
            - "8001:8000"
    objects-api:
        image: maykinmedia/objects-api:latest
        container_name: valtimo-academy-objects-api
        ports:
            - "8010:8000"
        environment:
            - CORS_ALLOW_ALL_ORIGINS=true
            - SECRET_KEY=${SECRET_KEY:-1(@f(-6s_u(5fd&1sg^uvu2s(c-9sapw)1era8q&)g)h@cwxxg}
            - DJANGO_SETTINGS_MODULE=objects.conf.docker
            - OBJECTS_SUPERUSER_PASSWORD=admin
            - OBJECTS_SUPERUSER_USERNAME=admin
            - DB_PORT=5432
            - DB_HOST=postgis
            - DB_USER=postgres
            - DB_PASSWORD=postgres
            - DB_NAME=objecten
            - DEBUG=true
            - TWO_FACTOR_FORCE_OTP_ADMIN=False
            - TWO_FACTOR_PATCH_ADMIN=False
    objecttypes-api:
        image: maykinmedia/objecttypes-api:1.1.1
        container_name: valtimo-academy-objecttypes-api
        ports:
            - "8011:8000"
        environment:
            - CORS_ALLOW_ALL_ORIGINS=true
            - SECRET_KEY=${SECRET_KEY:-fgv=c0hz&tl*8*3m3893@m+1pstrvidc9e^5@fpspmg%cy$$15d}
            - DJANGO_SETTINGS_MODULE=objecttypes.conf.docker
            - DB_PORT=5432
            - DB_HOST=postgres
            - DB_NAME=objecttypen
            - DB_USER=postgres
            - DB_PASSWORD=postgres
            - DEBUG=true
            - TWO_FACTOR_FORCE_OTP_ADMIN=False
            - TWO_FACTOR_PATCH_ADMIN=False
    open-notificaties:
        image: openzaak/open-notificaties:1.2.1
        container_name: valtimo-academy-opennotificaties
        ports:
            - "8002:8000"
        environment: &notificaties-env
            - DJANGO_SETTINGS_MODULE=nrc.conf.docker
            - SECRET_KEY=${SECRET_KEY:-4wHY2Cp5`4(q%)]cuWxPQJRp5kN?g+`.Xah>%6Fsq6+)R>p_}
            - ALLOWED_HOSTS=*
            - CACHE_DEFAULT=redis:6379/0
            - CACHE_AXES=redis:6379/1
            - DB_PORT=5432
            - DB_HOST=postgis
            - DB_NAME=opennotificaties
            - DB_USER=postgres
            - DB_PASSWORD=postgres
            - DEBUG=true
            - RABBITMQ_HOST=rabbitmq
            - PUBLISH_BROKER_URL=redis://redis:6379/0
            - CELERY_BROKER_URL=redis://redis:6379/0
            - CELERY_RESULT_BACKEND=redis://redis:6379/0
            - CELERY_LOGLEVEL=DEBUG
            - CELERY_WORKER_CONCURRENCY=${CELERY_WORKER_CONCURRENCY:-4}
    open-notificaties-celery:
        image: openzaak/open-notificaties:1.2.3
        container_name: valtimo-academy-opennotificaties-celery
        environment: *notificaties-env
        command: /celery_worker.sh
    sdk-openformulieren:
        image: openformulieren/open-forms-sdk:sprint-10
        container_name: valtimo-academy-sdk-openformulieren
        platform: linux/amd64
        ports:
            - "8005:80"
    web-openformulieren:
        image: openformulieren/open-forms:sprint-10
        container_name: valtimo-academy-web-openformulieren
        platform: linux/amd64
        environment: &web_env
            - CORS_ALLOW_ALL_ORIGINS=true
            - DJANGO_SETTINGS_MODULE=openforms.conf.docker
            - SECRET_KEY=${SECRET_KEY:-@r0w-0(&apjfde5fl6h23!vn)r1ldkp1c_d2#!$$did4z5hun4a}
            - DB_NAME=openformulieren
            - DB_USER=postgres
            - DB_PASSWORD=postgres
            - DB_HOST=postgres
            - CACHE_DEFAULT=redis:6379/0
            - CACHE_AXES=redis:6379/0
            - ALLOWED_HOSTS=*
            - CELERY_BROKER_URL=redis://redis:6379/0
            - CELERY_RESULT_BACKEND=redis://redis:6379/0
            - CELERY_LOGLEVEL=DEBUG
            - SDK_BASE_URL=${SDK_BASE_URL:-http://localhost:8005}
            - OPENFORMS_LOCATION_CLIENT=${OPENFORMS_LOCATION_CLIENT:-openforms.contrib.bag.client.BAGClient}
            # Needed for Celery Flower to match the TIME_ZONE configured in the
            # settings used by workers and beat containers.
            - TZ=Europe/Amsterdam
            - TWO_FACTOR_FORCE_OTP_ADMIN=False
            - TWO_FACTOR_PATCH_ADMIN=False
        ports:
            - "8003:8000"
        depends_on:
            - postgres
            - sdk-openformulieren
    celery-openformulieren:
        image: openformulieren/open-forms:sprint-10
        container_name: valtimo-academy-celery-openformulieren
        platform: linux/amd64
        environment: *web_env
        command: /celery_worker.sh
        depends_on:
            - postgres
            - redis
    celery-beat:
        image: openformulieren/open-forms:sprint-10
        container_name: valtimo-academy-celery-beat
        platform: linux/amd64
        environment: *web_env
        command: /celery_beat.sh
        depends_on:
            - postgres
            - redis
    celery-flower:
        image: mher/flower:0.9.7
        container_name: valtimo-academy-celery-flower
        platform: linux/amd64
        environment: *web_env
        ports:
            - "5555:5555"
        depends_on:
            - redis
            - celery-openformulieren
    web-openklant:
        image: maykinmedia/open-klant:latest
        container_name: valtimo-academy-web-openklant
        platform: linux/amd64
        environment:
            - DJANGO_SETTINGS_MODULE=openklant.conf.docker
            - SECRET_KEY=${SECRET_KEY:-django-insecure-$$8s@b*ds4t84-q_2#c0j0506@!l2q6r5_pq5e!vm^_9c*#^66b}
            - DB_NAME=openklant
            - DB_USER=postgres
            - DB_PASSWORD=postgres
            - DB_HOST=postgres
            - CACHE_DEFAULT=redis:6379/0
            - CACHE_AXES=redis:6379/0
            - ALLOWED_HOSTS=*
        ports:
            - "8006:8000"
        depends_on:
            - postgres
    keycloak:
        image: jboss/keycloak:15.0.0
        container_name: valtimo-academy-keycloak
        ports:
            - "8081:8080"
        environment:
            KEYCLOAK_USER: admin
            KEYCLOAK_PASSWORD: admin
            DB_VENDOR: postgres
            DB_ADDR: postgres
            DB_USER: postgres
            DB_PASSWORD: postgres