version: '3.9'
services:
    # databases
    postgis:
        image: ritense/valtimo-academy-postgis:0.0.9
        container_name: valtimo-academy-postgis
        platform: linux/amd64
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - PGDATA=/data
    postgres:
        image: ritense/valtimo-academy-postgres:0.0.8
        container_name: valtimo-academy-postgres
        platform: linux/amd64
        ports: 
            - "54321:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - PGDATA=/data
            
    mysql:
        image: mysql/mysql-server:8.0.28-1.2.7-server # version of oracle managed image that works on x86 and arm64
        container_name: valtimo-academy-mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: gzac
            MYSQL_USER: gzac
            MYSQL_PASSWORD: password
            MYSQL_ROOT_HOST: "%"
        command: [
                "--default-authentication-plugin=mysql_native_password",
                "--lower_case_table_names=1",
                "--collation-server=utf8mb4_unicode_ci",
                "--character-set-server=utf8mb4",
                "--explicit_defaults_for_timestamp",
                "--ssl=false",
                "--innodb_flush_method=O_DIRECT",
                "--sql_mode=NO_ENGINE_SUBSTITUTION"
        ]
        volumes:
            - gzac-database:/var/lib/mysql # persist data even if container shuts down
            
    #hulp services
    redis:
        image: redis:6.2.6
        container_name: valtimo-academy-redis
    rabbitmq:
        image: rabbitmq:3.9-management
        container_name: valtimo-academy-rabbitmq
        expose:
            - 5673
            - 15673
        ports:
            - "5673:5673"
            - "15673:15673"
        
    #zgw services    
    openzaak:
        image: openzaak/open-zaak:1.5.0
        container_name: valtimo-academy-openzaak
        platform: linux/amd64
        environment:
            - DB_HOST=postgis
            - DB_POST=5432
            - SECRET_KEY=veryRestrictedSecretKey
            - DB_USER=postgres
            - DB_PASSWORD=postgres
            - DB_NAME=openzaak
            - CACHE_DEFAULT=redis:6379/0
            - CACHE_AXES=redis:6379/0
            - DEBUG=true
            - ALLOWED_HOSTS=localhost,host.docker.internal,172.17.0.1,openzaak
            - SENDFILE_BACKEND=django_sendfile.backends.simple
        ports:
            - "8001:8000"
    objects-api:
        image: maykinmedia/objects-api:latest
        container_name: valtimo-academy-objects-api
        ports:
            - "8010:8000"
        environment:
            - CORS_ALLOW_ALL_ORIGINS=true
            - SECRET_KEY=${SECRET_KEY:-1(@f(-6s_u(5fd&1sg^uvu2s(c-9sapw)1era8q&)g)h@cwxxg}
            - DJANGO_SETTINGS_MODULE=objects.conf.docker
            - OBJECTS_SUPERUSER_PASSWORD=admin
            - OBJECTS_SUPERUSER_USERNAME=admin
            - DB_PORT=5432
            - DB_HOST=postgis
            - DB_USER=postgres
            - DB_PASSWORD=postgres
            - DB_NAME=objecten
            - DEBUG=true
            - TWO_FACTOR_FORCE_OTP_ADMIN=False
            - TWO_FACTOR_PATCH_ADMIN=False
    objecttypes-api:
        image: maykinmedia/objecttypes-api:1.1.1
        container_name: valtimo-academy-objecttypes-api
        ports:
            - "8011:8000"
        environment:
            - CORS_ALLOW_ALL_ORIGINS=true
            - SECRET_KEY=${SECRET_KEY:-fgv=c0hz&tl*8*3m3893@m+1pstrvidc9e^5@fpspmg%cy$$15d}
            - DJANGO_SETTINGS_MODULE=objecttypes.conf.docker
            - DB_PORT=5432
            - DB_HOST=postgres
            - DB_NAME=objecttypen
            - DB_USER=postgres
            - DB_PASSWORD=postgres
            - DEBUG=true
            - TWO_FACTOR_FORCE_OTP_ADMIN=False
            - TWO_FACTOR_PATCH_ADMIN=False
    open-notificaties:
        image: openzaak/open-notificaties:1.2.1
        container_name: valtimo-academy-opennotificaties
        ports:
            - "8002:8000"
        environment: &notificaties-env
            - DJANGO_SETTINGS_MODULE=nrc.conf.docker
            - SECRET_KEY=${SECRET_KEY:-4wHY2Cp5`4(q%)]cuWxPQJRp5kN?g+`.Xah>%6Fsq6+)R>p_}
            - ALLOWED_HOSTS=*
            - CACHE_DEFAULT=redis:6379/0
            - CACHE_AXES=redis:6379/1
            - DB_PORT=5432
            - DB_HOST=postgis
            - DB_NAME=opennotificaties
            - DB_USER=postgres
            - DB_PASSWORD=postgres
            - DEBUG=true
            - RABBITMQ_HOST=rabbitmq
            - PUBLISH_BROKER_URL=redis://redis:6379/0
            - CELERY_BROKER_URL=redis://redis:6379/0
            - CELERY_RESULT_BACKEND=redis://redis:6379/0
            - CELERY_LOGLEVEL=DEBUG
            - CELERY_WORKER_CONCURRENCY=${CELERY_WORKER_CONCURRENCY:-4}
    open-notificaties-celery:
        image: openzaak/open-notificaties:1.2.3
        container_name: valtimo-academy-opennotificaties-celery
        environment: *notificaties-env
        command: /celery_worker.sh
    keycloak:
        image: jboss/keycloak:15.0.0
        container_name: valtimo-academy-keycloak
        ports:
            - "8081:8080"
        environment:
            KEYCLOAK_USER: admin
            KEYCLOAK_PASSWORD: admin
            DB_VENDOR: postgres
            DB_ADDR: postgres
            DB_USER: postgres
            DB_PASSWORD: postgres
        user: root
    gzac-backend:
        image: ritense/valtimo-academy-gzac-backend:0.0.1
        container_name: valtimo-academy-gzac-backend
        ports:
            - "8080:8080"
        depends_on:
            - mysql
        environment:
            SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/gzac
            SPRING_DATASOURCE_USERNAME: gzac
            SPRING_DATASOURCE_PASSWORD: password
            VALTIMO_JWT_SECRET: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAooyECQIi6v4TLKOYWwXClDhJcrGcGfKZj7LQIgY/Ajm2nAKv5kiZRoS8GzMzIGKkkilAJyWQCoKlP//azHqzIxO6WZWCqGFxd04vK5JYujsiMMTNvTggfFSM7VxbzU/wv+aAEvBaGUMYp2Oamn5szzYzkzsowujvDZp+CE8ryZWTVmA+8WZE4aoU6VzfXmMDmPxvRXvktPRsJkA7hkv65TTJwUZF38goRg62kRD0hOP1sIy6vwKDSkjafLV1bYNBRiWXNReJNBXauhy74GeiHODGrI62NwUJXSgZ62cViPt6cx/3A7VBPLpEPnpnlZcIDfsFpSUuNEXc7HoLRuldbQIDAQAB
            KEYCLOAK_REALM: valtimo
            KEYCLOAK_AUTH_SERVER_URL: https://localhost:8081/auth
            KEYCLOAK_RESOURCE: valtimo-m2m-client
            KEYCLOAK_CREDENTIALS_SECRET: 6ef6ca16-6b86-482a-a3d9-0561704c1db9
    gzac-frontend:
        image: ritense/valtimo-academy-gzac-frontend:0.0.1
        container_name: valtimo-academy-gzac-frontend
        ports:
            - "4200:80"
        environment:    
            API_URI: http://localhost:8080/api/ 
            MOCK_API_URI: http://localhost:8080/mock-api/ 
            SWAGGER_URI: http://localhost:8080/v2/api-docs 
            KEYCLOAK_URL: http://keycloak.k8s.academy.gzac.nl/auth
            KEYCLOAK_REALM: valtimo
            KEYCLOAK_CLIENT_ID: valtimo-console
            KEYCLOAK_REDIRECT_URI: http://localhost:4200
            KEYCLOAK_LOGOUT_REDIRECT_URI: http://localhost:4200
            WHITELISTED_DOMAIN: localhost:4200
volumes:
    gzac-database: